//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ef
{
    using System;
    using System.Collections.Generic;
    
    public partial class buyer
    {
        public int id_buyer { get; set; }
        public string namebuyer { get; set; }
        public string surname { get; set; }
        public string patronymic { get; set; }
        public string numbertelephon { get; set; }
        public string gender { get; set; }
        public int buyer_ID { get; set; }
    
        public virtual sellers sellers { private get; set; }
    }
}
